
languageCode = 'en-us'
title = 'Nim PyLib Site'
theme = 'ananke'


menus.main = [
    {weight=10, name = 'Docs', url = 'https://docs.nimpylib.org'},
    {weight=20, name = "Donate", url = "/donate/"},
    {weight=30, name = 'Repo', url = 'https://github.com/nimpylib/pylib'},
    {weight=40, name = 'Wiki', url = 'https://github.com/nimpylib/pylib/wiki'},
    {weight=50, name = 'Install', url = '/install/'},
    {weight=60, name = 'Online Demo', url = 'https://play.nimpylib.org'},
]

# We used to use `[[menus.main]]`, but that's too many lines

[Params]
  RepoURL = 'https://github.com/nimpylib/pylib'  

  body_classes = "avenir bg-light-gray"

  recent_copy = "About"  # default: i18n "recentTitle" -> "Recent Posts"
  # We use it as a place for "about" instead of "Posts"

  read_more_copy = "details"  # default: i18n "readMore" -> "read more"

  [Params.codeRepo]
    user = "nimpylib"
    repo = "pylib"
    commit = "master"

  [Params.ananke.social.github]
    username = "nimpylib"

  [Params.ananke.social.follow]
    new_window_icon = true
    networks = ['github']

# allow inline html in Markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
