
languageCode = 'en-us'
title = 'Nim PyLib Site'
theme = 'ananke'


[menus]
  [[menus.main]]
    name = 'Docs'
    url = 'https://docs.nimpylib.org/'

  [[menus.main]]
    name = "Donate"
    url = "/donate/"

  [[menus.main]]
    name = 'Repo'
    url = 'https://github.com/nimpylib/pylib'

  [[menus.main]]
    name = 'Wiki'
    url = 'https://github.com/nimpylib/pylib/wiki'

[Params]
  RepoURL = 'https://github.com/nimpylib/pylib'  

  body_classes = "avenir bg-light-gray"

# allow inline html in Markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
